CREATE DAtABASE PerfumeShop

CREATE TABLE Brand(
Id INT PRIMARY KEY(Id) IDENTITY(1,1) NOT NULL,
[Name] NVARCHAR(50)
)

CREATE TABLE Perfume(
Id INT PRIMARY KEY(Id) IDENTITY(1,1) NOT NULL,
BrandId INT FOREIGN KEY(BrandId) REFERENCES Brand(Id),
[Name] NVARCHAR(50),
Gender BIT,
IsPerfume BIT
)

CREATE TABLE PerfumePrice(
Id INT PRIMARY KEY(Id) IDENTITY(1,1) NOT NULL,
PerfumeId INT FOREIGN KEY(PerfumeID) REFERENCES Perfume(Id),
Size INT,
Price DECIMAL
)
